version: "3.7"
services:
  emp-app-db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - emp-app-network

  emp-micro-service:
    depends_on:
      - emp-app-db
    image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/equitas-it:emp-micro-service
    environment:
      - dbUrl=jdbc:mysql://emp-app-db:3306/bank1?createDatabaseIfNotExist=true
    ports:
      - 8081:8081
    networks:
      - emp-app-network
    restart: on-failure

  emp-ui-app-service:
    depends_on:
      - emp-micro-service
    image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/equitas-it:emp-ui-app
    environment:
      - empMgmtApiUrl=http://emp-micro-service:8081/emp
#    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/backend-proxy.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 4200:80
    networks:
      - emp-app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8980:8080
    networks:
      - emp-app-network

networks:
  emp-app-network:
    driver: bridge