apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  containers:
    - name: mysql
      image: mysql:5.7
      volumeMounts:
        - name: mysql-etc
          mountPath: /etc/mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
  volumes:
    - name: mysql-etc
      hostPath:
        path: /etc/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
