apiVersion: apps/v1
kind: Deployment
metadata:
  name: emp-ui-ms-deployment
  labels:
    app: emp-ui-ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emp-ui-ms
  template:
    metadata:
      labels:
        app: emp-ui-ms
    spec:
      containers:
      - name: emp-ui-ms
        image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/equitas-it:emp-ui-app
        env: 
        - name: empMgmtApiUrl
          valueFrom:
            configMapKeyRef: 
              name: emp-app-config
              key: empMgmtApiUrl
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 128Mi
            cpu: "0.2"        

---

apiVersion: v1
kind: Service
metadata:  
  name: emp-ui-app-service
spec:
  type: NodePort  
  selector:
    app: emp-ui-ms
  ports:
    - protocol: TCP
      # nodePort: 30101
      port: 4200
      targetPort: 80