apiVersion: apps/v1
kind: Deployment
metadata:
  name: emp-ms-deployment
  labels:
    app: emp-ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emp-ms
  template:
    metadata:
      labels:
        app: emp-ms
    spec:
      containers:
      - name: emp-ms
        image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/equitas-it:emp-micro-service
        ports:
        - containerPort: 8081
        env: 
        - name: dbUser
          valueFrom:
            secretKeyRef:
              name: emp-app-secret
              key: db_user
        - name: dbPwd
          valueFrom:
            secretKeyRef: 
              name: emp-app-secret
              key: db_pwd
        - name: dbUrl
          valueFrom: 
            configMapKeyRef: 
              name: emp-app-config
              key: mysqlDBUrl  

        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 128Mi
            cpu: "0.2"        

---

apiVersion: v1
kind: Service
metadata:
  type: NodePort
  name: emp-micro-service
spec:
  selector:
    app: emp-micro
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30010